import { execSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { parse } from "dotenv";
import { requireVercelCliToken } from "../src/lib/vercel-cli-auth";

const OUT_FILE = ".env.payments.local";
const LISTENER_KEYS = [
  "DATABASE_URL",
  "RECEIVING_WALLET",
  "BSC_RPC_URL",
  "BSC_CHAIN_ID",
  "BSC_USDT_CONTRACT",
  "ENABLE_UNIQUE_DEPOSIT_ADDRESSES",
  "DEPOSIT_MNEMONIC",
  "ENABLE_DEPOSIT_SWEEPER",
  "TREASURY_PRIVATE_KEY",
  "PAYMENT_CONFIRMATIONS",
  "PAYMENT_LISTENER_POLL_MS",
  "CRON_SECRET",
  "AUTH_SECRET",
];

function readRepoMeta() {
  const repoPath = path.join(process.cwd(), ".vercel", "repo.json");
  if (!fs.existsSync(repoPath)) {
    throw new Error("Project not linked. Run `vercel link` in the project root.");
  }
  return JSON.parse(fs.readFileSync(repoPath, "utf8")) as {
    projects?: { name: string; orgId: string }[];
  };
}

function vercelApiJson(apiPath: string): unknown {
  const out = execSync(`npx vercel api "${apiPath}" --raw`, {
    encoding: "utf8",
    stdio: ["pipe", "pipe", "pipe"],
  });
  const jsonStart = out.indexOf("{");
  const arrStart = out.indexOf("[");
  const start =
    jsonStart === -1 ? arrStart : arrStart === -1 ? jsonStart : Math.min(jsonStart, arrStart);
  if (start === -1) throw new Error(`Unexpected vercel api output for ${apiPath}`);
  return JSON.parse(out.slice(start));
}

async function fetchProductionEnvValues(teamId: string, projectName: string) {
  const list = vercelApiJson(
    `/v10/projects/${projectName}/env?teamId=${teamId}`
  ) as { envs?: { id: string; key: string; type: string }[] };

  const values = new Map<string, string>();

  for (const env of list.envs ?? []) {
    if (!LISTENER_KEYS.includes(env.key)) continue;

    const detail = vercelApiJson(
      `/v1/projects/${projectName}/env/${env.id}?teamId=${teamId}`
    ) as { key?: string; value?: string; type?: string };

    if (detail.value) {
      values.set(env.key, detail.value);
    }
  }

  return values;
}

function writeEnvFile(filePath: string, vars: Map<string, string>) {
  const lines = [
    "# Auto-generated by npm run payments:env:sync — do not commit",
    `# ${new Date().toISOString()}`,
    "",
  ];

  for (const key of LISTENER_KEYS) {
    const value = vars.get(key);
    if (value) {
      lines.push(`${key}=${JSON.stringify(value)}`);
    }
  }

  fs.writeFileSync(filePath, lines.join("\n") + "\n", "utf8");
}

function mergePulledFile(filePath: string, into: Map<string, string>) {
  if (!fs.existsSync(filePath)) return;
  const parsed = parse(fs.readFileSync(filePath, "utf8"));
  for (const [key, value] of Object.entries(parsed)) {
    if (value && (!into.has(key) || !into.get(key))) {
      into.set(key, value);
    }
  }
}

async function main() {
  requireVercelCliToken();
  readRepoMeta();

  console.log("[payments:env:sync] Pulling Development environment variables from Vercel…");
  execSync(`npx vercel env pull ${OUT_FILE} --environment=development --yes`, {
    stdio: "inherit",
  });

  const vars = new Map<string, string>();
  mergePulledFile(OUT_FILE, vars);

  const repo = readRepoMeta();
  const project = repo.projects?.[0];
  if (project?.name && project?.orgId) {
    console.log("[payments:env:sync] Merging any readable Production values from Vercel API…");
    try {
      const prod = await fetchProductionEnvValues(project.orgId, project.name);
      for (const [key, value] of prod) {
        if (!vars.get(key)) vars.set(key, value);
      }
    } catch (error) {
      console.warn("[payments:env:sync] Could not read production values:", error);
    }
  }

  writeEnvFile(OUT_FILE, vars);

  const missing = LISTENER_KEYS.filter(
    (key) => !vars.get(key) && key !== "BSC_USDT_CONTRACT" && key !== "AUTH_SECRET"
  );

  const hasListener =
    (vars.get("RECEIVING_WALLET") && vars.get("BSC_RPC_URL")) ||
    (vars.get("ENABLE_UNIQUE_DEPOSIT_ADDRESSES") === "true" && vars.get("DEPOSIT_MNEMONIC"));

  console.log(`\n[payments:env:sync] Wrote ${OUT_FILE} (${vars.size} variables).`);

  if (!hasListener) {
    console.log(
      "\nVercel marks Production secrets as *sensitive* — they cannot be exported to disk."
    );
    console.log("Use remote listener instead (recommended):");
    console.log("  vercel login");
    console.log("  npm run payments:listen");
    console.log("\nOptional — enable local mode by adding the same keys to the");
    console.log("Development environment in Vercel (Dashboard → Settings → Environment Variables),");
    console.log("then run `npm run payments:env:sync` again.");
    if (missing.length) {
      console.log("\nStill missing for local mode:", missing.join(", "));
    }
    process.exit(missing.length > 0 ? 1 : 0);
  }

  console.log("\nLocal listener ready. Run:");
  console.log("  PAYMENTS_LISTEN_MODE=local npm run payments:listen");
}

main().catch((error) => {
  console.error("[payments:env:sync] Failed:", error instanceof Error ? error.message : error);
  process.exit(1);
});
